In [118]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
# from pathlib import Path
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
from imblearn.ensemble import BalancedRandomForestClassifier



In [119]:
import numpy as np

In [120]:
df_1 = pd.read_csv('/Users/savannahposner/Desktop/bigProject/Tennessee_Tornadoes/Updated_Cleaned.csv')
df_1


Unnamed: 0  Unnamed: 0.1    FID    YR  MO        DATE      TIME  MAG  \
0              0             0  23025  2011   4  2011-04-09  14:35:00    0   
1              1             1  23027  2011   4  2011-04-09  16:00:00    1   
2              2             2  23028  2011   4  2011-04-09  16:08:00    1   
3              3             3  23029  2011   4  2011-04-09  16:15:00    0   
4              4             4  23044  2011   4  2011-04-27  19:07:00    0   
...          ...           ...    ...   ...  ..         ...       ...  ...   
1109        1109          1109  28915  1967   7  1967-07-05  14:25:00    1   
1110        1110          1110  28916  1991  11  1991-11-19  17:05:00    1   
1111        1111          1111  28926  1992   3  1992-03-18  08:20:00    0   
1112        1112          1112  28962  1974   6  1974-06-07  11:30:00    1   
1113        1113          1113  28984  2013   5  2013-05-31  05:05:00    1   

         SLAT     SLON     ELAT     ELON    LEN  WID  Fatalities  Injuries  \
0     36.2971 -82.3174  36.2934 -82.3021   0.89   50           0         0   
1     36.3000 -82.4341  36.3000 -82.4341   3.00  150           0         0   
2     36.3037 -82.3923  36.3099 -82.3846   0.61  100           0         0   
3     36.0424 -82.5568  36.0477 -82.5393   1.04   50           0         0   
4     36.2255 -83.0570  36.2263 -83.0486   0.50   70           0         0   
...       ...      ...      ...      ...    ...  ...         ...       ...   
1109  35.0000 -90.0000   0.0000   0.0000   0.10   10           0         0   
1110  35.1300 -90.0200  35.2800 -89.9300  10.00   50           0         0   
1111  35.2200 -89.7700   0.0000   0.0000   1.50   50           0         0   
1112  35.5700 -89.6500   0.0000   0.0000   0.30  100           1         1   
1113  35.6159 -89.7031  35.6142 -89.6884   0.83  250           0         0   

      Property Loss    starting county      ending county  
0               4.0      Carter County      Carter County  
1               5.0  Washington County  Washington County  
2               4.0  Washington County  Washington County  
3               4.0      Unicoi County      Unicoi County  
4               3.0      Greene County      Greene County  
...             ...                ...                ...  
1109            4.0      Shelby County                NaN  
1110            6.0      Shelby County      Shelby County  
1111            4.0      Shelby County                NaN  
1112            4.0      Tipton County                NaN  
1113            5.0      Tipton County      Tipton County  

[1114 rows x 19 columns]

In [121]:
# East_TN = ["Anderson County","Blount County","Campbell County","Carter County","Claiborne County","Cocke County","Grainger County","Hamblen County","Hancock County""Hawkins County","Jefferson County","Johnson County","Knox County","Loudon County""McMinn County","Monroe County""Morgan County","Roane County""Scott County","Sevier County","Sullivan County","Unicoi County","Union County","Washington County"]


# West_TN =["Benton County","Carroll County","Chester County","Crockett County","Decatur County","Dyer County","Fayette County","Gibson County","Hardeman County","Hardin County","Haywood County","Henderson County","Henry County","Lake County","Lauderdale County","Madison County","McNairy County","Obion County","Shelby County","Tipton County","Weakley County"]


# Middle_TN = ["Bedford County","Cannon County","Cheatham County","Clay County","Davidson County","DeKalb County","Dickson County","Fentress County","Franklin County","Giles County","Grundy County","Hickman County","Houston County","Humphreys County","Jackson County","Lawrence County","Lewis County","Lincoln County","Macon County","Marshall County","Maury County","Montgomery County""Moore County","Overton County","Perry County","Pickett County","Putnam County","Robertson County","Rutherford County","Sequatchie County","Smith County","Stewart County","Sumner County","Trousdale County","Van Buren County","Warren County","Wayne County","White County","Williamson County","Wilson County"]




# for x in range(0,len(df_1["starting county"])): 
#     #for e in range(0,len(East_TN)): 
#         if df_1['starting county'][x] in East_TN:
#             df_1['Tennessee Area'] = 'E'
            
#  #   for e in range(0,len(Middle_TN)): 
#         if  df_1['starting county'][x] in Middle_TN:
#             df_1['Tennessee Area'] = 'M'
            
            
#   # for e in range(0,len(West_TN)): 
#         if  df_1['starting county'][x] in West_TN:
#             df_1['Tennessee Area'] = 'W'
#         x = x+1

        
    

# df_1["Tennessee Area"]


In [122]:
df_1 = df_1.dropna()
df_1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'FID', 'YR', 'MO', 'DATE', 'TIME', 'MAG',
       'SLAT', 'SLON', 'ELAT', 'ELON', 'LEN', 'WID', 'Fatalities', 'Injuries',
       'Property Loss', 'starting county', 'ending county'],
      dtype='object')

In [139]:
# df = df_1.drop([ 'YR','Unnamed: 0','Unnamed: 0.1','DATE','TIME',
#                'SLAT','SLON','ELAT','ELON','LEN','ending county'], axis=1)

df = df_1.drop(['Unnamed: 0','Unnamed: 0.1','TIME',
              'SLAT','SLON','ELAT','ELON','LEN','ending county','Injuries','FID'], axis=1)
df.columns

Index(['YR', 'MO', 'DATE', 'MAG', 'WID', 'Fatalities', 'Property Loss',
       'starting county'],
      dtype='object')

In [140]:
df
# Date, Starting county, property loss 

# Magnitude, DATE, MO, STARTING COUNTY,YR, WID,
#STARTING COUNTy 

YR  MO        DATE  MAG  WID  Fatalities  Property Loss  \
0     2011   4  2011-04-09    0   50           0            4.0   
1     2011   4  2011-04-09    1  150           0            5.0   
2     2011   4  2011-04-09    1  100           0            4.0   
3     2011   4  2011-04-09    0   50           0            4.0   
4     2011   4  2011-04-27    0   70           0            3.0   
...    ...  ..         ...  ...  ...         ...            ...   
1103  2009   6  2009-06-12    1   30           0            4.0   
1104  2009   7  2009-07-30    1  250           0            5.0   
1107  2010   5  2010-05-01    1  100           0            4.0   
1110  1991  11  1991-11-19    1   50           0            6.0   
1113  2013   5  2013-05-31    1  250           0            5.0   

        starting county  
0         Carter County  
1     Washington County  
2     Washington County  
3         Unicoi County  
4         Greene County  
...                 ...  
1103      Shelby County  
1104      Shelby County  
1107      Shelby County  
1110      Shelby County  
1113      Tipton County  

[686 rows x 8 columns]

In [154]:
# Create our features

target = 'MO'
X = pd.get_dummies(df.drop(columns=target))


# Create our target
y = df[target]

In [155]:

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)

### Run through the Models Provided in the Module 17 

In [156]:
x ="An Error as occured"
try:

    print(f"naive random oversampling\n")
# Resample the training data with the RandomOversampler

    ros = RandomOverSampler(random_state=1)
    X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
    Counter(y_resampled)
# Train the Logistic Regression model using the resampled data
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Display the confusion matrix
    y_pred = model.predict(X_test)
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
except:
      print(x)



# Calculated the balanced accuracy score
try:

    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")

# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

# Resample the training data with SMOTE
    print(f"SMOTE\n")
    X_resampled, y_resampled = SMOTE(random_state=1,
    sampling_strategy='auto').fit_resample(
       X_train, y_train)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

except:
      print(x)
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
# Resample the training data with SMOTE

try: 
    print(f"Random Under Sampler\n")
    ros = RandomUnderSampler(random_state=1)
    X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:
      print(x)
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
# YOUR CODE HERE
try:
    print(f"SMOTEENN\n")
    smote_enn = SMOTEENN(random_state=0)
    X_resampled, y_resampled = smote_enn.fit_resample(X, y)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:  
      print(x)


# Resample the training data with the BalancedRandomForestClassifier
try:
    print(f"Balanced Random Forest Classifier \n")
    model = BalancedRandomForestClassifier(n_estimators =100, random_state=1)
    model = model.fit(X_train, y_train)
    # Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:
    print(x)

# Train the EasyEnsembleClassifier
try:
    print(f"Easy Ensemble Classifier \n")

# Train the EasyEnsembleClassifier
    from imblearn.ensemble import EasyEnsembleClassifier 
    model = EasyEnsembleClassifier(n_estimators =100, random_state=1)
    model.fit(X_train, y_train)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
    
except:
    print(x)

naive random oversampling

Confusion Matrix:
[[ 0  3  0  0  0  0  2  0  3  0  0  2]
 [ 1  5  0  0  0  0  1  0  2  1  1  4]
 [ 2  8  1  0  2  0  2  0  3  2  0  0]
 [ 2 13  2  0  6  0 10  1 15  2  1  0]
 [ 7  3  0  0  3  0  5  0  9  1  1  3]
 [ 0  1  0  0  1  0  0  1  3  1  0  1]
 [ 0  0  0  0  0  0  0  0  1  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0]
 [ 1  1  0  0  1  0  2  0  4  1  0  1]
 [ 1  5  0  0  1  0  7  0  2  0  1  2]
 [ 0  0  0  0  0  0  0  0  1  0  0  0]]

The accuracy score: 
0.056420363926344794

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.00      0.00      0.91      0.00      0.00      0.00        10
          2       0.13      0.33      0.78      0.19      0.51      0.25        15
          3       0.33      0.05      0.99      0.09      0.22      0.04        20
          4       0.00      0.00      1.00      0.00      0.00      0.00        52
   

### Additional Machine Learning Models that we can try 

#### SGDClassifier 

link to reference: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html

In [157]:
#sklearn.linear_model.SGDClassifier


# This estimator implements regularized linear models with stochastic gradient descent (SGD) learning: 
#     the gradient of the loss is estimated each sample at a time and the model is updated 
#     along the way with a decreasing strength schedule (aka learning rate).

from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
# X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
# Counter(y_resampled)

model = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3))
model.fit(X_train, y_train)

# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.5333639347096285

Confusion Matrix:
[[ 9  0  0  1  0  0  0  0  0  0  0]
 [ 0 14  0  1  0  0  0  0  0  0  0]
 [ 0  0 17  2  1  0  0  0  0  0  0]
 [ 0  0  0 51  0  1  0  0  0  0  0]
 [ 0  0  0  6 25  1  0  0  0  0  0]
 [ 0  0  0  7  0  1  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  5  0  0]
 [ 0  0  0  3  0  0  0  0  0 16  0]
 [ 0  0  0  1  0  0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       1.00      0.90      1.00      0.95      0.95      0.89        10
          2       1.00      0.93      1.00      0.97      0.97      0.93        15
          3       1.00      0.85      1.00      0.92      0.92      0.84        20
          4       0.62      0.98      0.74      0.76      0.85      0.74        52
          5       0.96      0.78      0.99      0.86      0.88      0.76        32
          6       0.3

#### GaussianNB

link to reference: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

In [158]:
# When performing classification you often want to predict not only the class label, 
# but also the associated probability. 
# This probability gives you some kind of confidence on the prediction

from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import brier_score_loss
from sklearn.naive_bayes import GaussianNB

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

model = GaussianNB()
model.fit(X_train, y_train)  # GaussianNB itself does not support sample-weights


# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.4282403302439187

Confusion Matrix:
[[ 8  0  0  0  0  1  0  0  0  1  0  0]
 [ 0 12  0  0  0  1  1  1  0  0  0  0]
 [ 0  1  9  1  1  1  0  0  2  2  3  0]
 [ 2  2  1 38  0  4  0  2  0  1  1  1]
 [ 1  1  1  0 19  2  1  2  0  2  3  0]
 [ 0  0  1  2  0  2  2  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  1  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  1  0]
 [ 2  1  0  0  1  1  0  0  0  5  0  1]
 [ 1  0  0  0  0  3  1  1  0  1 12  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.57      0.80      0.96      0.67      0.88      0.76        10
          2       0.71      0.80      0.97      0.75      0.88      0.76        15
          3       0.75      0.45      0.98      0.56      0.66      0.42        20
          4       0.93      0.73      0.97      0.82      0.84      0.70        52
          5       0.86      0.59

 RandomOverSampler: Using differnt solvers

link to reference https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [159]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='liblinear', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.48835934798853453

Confusion Matrix:
[[ 9  0  1  0  0  0  0  0  0  0  0  0]
 [ 0 13  2  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  2  1  0  0  0  0  1  1  0]
 [ 0  1  3 36  4  3  0  1  1  0  1  2]
 [ 1  0  2  1 26  2  0  0  0  0  0  0]
 [ 0  0  2  2  1  2  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0  0  0  0  0]
 [ 2  0  1  1  2  0  0  0  0  4  0  1]
 [ 0  1  0  0  1  3  0  0  0  0 14  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.75      0.90      0.98      0.82      0.94      0.88        10
          2       0.87      0.87      0.99      0.87      0.93      0.85        15
          3       0.58      0.75      0.93      0.65      0.83      0.68        20
          4       0.84      0.69      0.94      0.76      0.81      0.64        52
          5       0.68      0.8

In [160]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='liblinear', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.48835934798853453

Confusion Matrix:
[[ 9  0  1  0  0  0  0  0  0  0  0  0]
 [ 0 13  2  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  2  1  0  0  0  0  1  1  0]
 [ 0  1  3 36  4  3  0  1  1  0  1  2]
 [ 1  0  2  1 26  2  0  0  0  0  0  0]
 [ 0  0  2  2  1  2  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0  0  0  0  0]
 [ 2  0  1  1  2  0  0  0  0  4  0  1]
 [ 0  1  0  0  1  3  0  0  0  0 14  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.75      0.90      0.98      0.82      0.94      0.88        10
          2       0.87      0.87      0.99      0.87      0.93      0.85        15
          3       0.58      0.75      0.93      0.65      0.83      0.68        20
          4       0.84      0.69      0.94      0.76      0.81      0.64        52
          5       0.68      0.8

In [161]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='sag', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.09573748619801252

Confusion Matrix:
[[ 0  3  0  0  0  0  2  4  0  1  0]
 [ 0  6  0  0  0  0  3  3  0  3  0]
 [ 3  8  1  0  1  0  4  3  0  0  0]
 [ 2 13  1  1  5  0  7 19  3  1  0]
 [ 7  3  0  1  1  0  7 10  1  2  0]
 [ 0  1  0  0  1  0  1  3  2  0  0]
 [ 0  0  0  0  0  0  1  1  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0]
 [ 1  1  0  0  1  0  2  6  0  0  0]
 [ 2  5  0  0  0  0  6  5  0  1  0]
 [ 0  0  0  0  0  0  0  1  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.00      0.00      0.91      0.00      0.00      0.00        10
          2       0.15      0.40      0.78      0.22      0.56      0.30        15
          3       0.50      0.05      0.99      0.09      0.22      0.04        20
          4       0.50      0.02      0.99      0.04      0.14      0.02        52
          5       0.11      0.03      0.94      0.05      0.17      0.03        32
          6       0.

In [162]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='newton-cg', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.5179541550953034

Confusion Matrix:
[[ 9  0  1  0  0  0  0  0  0  0  0  0]
 [ 0 13  2  0  0  0  0  0  0  0  0  0]
 [ 0  1 15  2  1  0  0  0  1  0  0  0]
 [ 0  1  4 38  4  3  0  1  0  0  0  1]
 [ 1  0  2  1 26  2  0  0  0  0  0  0]
 [ 0  0  2  2  1  2  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  0  0  0  0  0  0  0]
 [ 1  0  1  1  2  0  0  0  0  6  0  0]
 [ 0  0  0  0  1  2  0  0  0  0 16  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.75      0.90      0.98      0.82      0.94      0.88        10
          2       0.87      0.87      0.99      0.87      0.93      0.85        15
          3       0.56      0.75      0.92      0.64      0.83      0.68        20
          4       0.84      0.73      0.94      0.78      0.83      0.67        52
          5       0.70      0.81

In [163]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='saga', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.09119203165255797

Confusion Matrix:
[[ 0  3  0  0  0  0  2  4  0  1  0]
 [ 0  6  0  0  0  0  3  3  0  3  0]
 [ 5  8  0  0  0  0  4  3  0  0  0]
 [ 6 13  1  1  1  0  7 19  2  2  0]
 [ 6  3  0  1  1  0  7 10  0  4  0]
 [ 1  1  0  0  0  0  1  3  2  0  0]
 [ 0  0  0  0  0  0  1  1  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0]
 [ 2  1  0  0  0  0  2  6  0  0  0]
 [ 2  5  0  0  0  0  6  5  0  1  0]
 [ 0  0  0  0  0  0  0  1  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.00      0.00      0.86      0.00      0.00      0.00        10
          2       0.15      0.40      0.78      0.22      0.56      0.30        15
          3       0.00      0.00      0.99      0.00      0.00      0.00        20
          4       0.50      0.02      0.99      0.04      0.14      0.02        52
          5       0.50      0.03      0.99      0.06      0.18      0.03        32
          6       0.

In [164]:
from sklearn.pipeline import make_pipeline




ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = make_pipeline(StandardScaler(),LogisticRegression(solver='newton-cg'))
model.fit(X_train, y_train)

# model = LogisticRegression(solver='newton-cg', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")



The accuracy score: 
0.5425025233936717

Confusion Matrix:
[[ 9  0  1  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  1  0  0  0  0]
 [ 0  0 17  0  1  1  0  0  0  1  0  0]
 [ 0  2  0 45  0  2  0  2  0  1  0  0]
 [ 2  0  1  0 25  1  0  1  0  0  2  0]
 [ 1  0  1  2  0  2  1  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  1  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  1  0]
 [ 3  0  1  0  1  0  0  0  0  6  0  0]
 [ 0  0  0  0  1  2  0  0  0  0 16  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          1       0.60      0.90      0.96      0.72      0.93      0.86        10
          2       0.82      0.93      0.98      0.87      0.96      0.91        15
          3       0.81      0.85      0.97      0.83      0.91      0.82        20
          4       0.94      0.87      0.97      0.90      0.92      0.83        52
          5       0.89      0.78