In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
# from pathlib import Path
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
from imblearn.ensemble import BalancedRandomForestClassifier



In [2]:
import numpy as np

In [3]:
df_1 = pd.read_csv('/Users/savannahposner/Desktop/bigProject/Tennessee_Tornadoes/Updated_Cleaned.csv')
df_1


Unnamed: 0  Unnamed: 0.1    FID    YR  MO        DATE      TIME  MAG  \
0              0             0  23025  2011   4  2011-04-09  14:35:00    0   
1              1             1  23027  2011   4  2011-04-09  16:00:00    1   
2              2             2  23028  2011   4  2011-04-09  16:08:00    1   
3              3             3  23029  2011   4  2011-04-09  16:15:00    0   
4              4             4  23044  2011   4  2011-04-27  19:07:00    0   
...          ...           ...    ...   ...  ..         ...       ...  ...   
1109        1109          1109  28915  1967   7  1967-07-05  14:25:00    1   
1110        1110          1110  28916  1991  11  1991-11-19  17:05:00    1   
1111        1111          1111  28926  1992   3  1992-03-18  08:20:00    0   
1112        1112          1112  28962  1974   6  1974-06-07  11:30:00    1   
1113        1113          1113  28984  2013   5  2013-05-31  05:05:00    1   

         SLAT     SLON     ELAT     ELON    LEN  WID  Fatalities  Injuries  \
0     36.2971 -82.3174  36.2934 -82.3021   0.89   50           0         0   
1     36.3000 -82.4341  36.3000 -82.4341   3.00  150           0         0   
2     36.3037 -82.3923  36.3099 -82.3846   0.61  100           0         0   
3     36.0424 -82.5568  36.0477 -82.5393   1.04   50           0         0   
4     36.2255 -83.0570  36.2263 -83.0486   0.50   70           0         0   
...       ...      ...      ...      ...    ...  ...         ...       ...   
1109  35.0000 -90.0000   0.0000   0.0000   0.10   10           0         0   
1110  35.1300 -90.0200  35.2800 -89.9300  10.00   50           0         0   
1111  35.2200 -89.7700   0.0000   0.0000   1.50   50           0         0   
1112  35.5700 -89.6500   0.0000   0.0000   0.30  100           1         1   
1113  35.6159 -89.7031  35.6142 -89.6884   0.83  250           0         0   

      Property Loss    starting county      ending county  
0               4.0      Carter County      Carter County  
1               5.0  Washington County  Washington County  
2               4.0  Washington County  Washington County  
3               4.0      Unicoi County      Unicoi County  
4               3.0      Greene County      Greene County  
...             ...                ...                ...  
1109            4.0      Shelby County                NaN  
1110            6.0      Shelby County      Shelby County  
1111            4.0      Shelby County                NaN  
1112            4.0      Tipton County                NaN  
1113            5.0      Tipton County      Tipton County  

[1114 rows x 19 columns]

In [4]:
df_1 = df_1.dropna()
df_1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'FID', 'YR', 'MO', 'DATE', 'TIME', 'MAG',
       'SLAT', 'SLON', 'ELAT', 'ELON', 'LEN', 'WID', 'Fatalities', 'Injuries',
       'Property Loss', 'starting county', 'ending county'],
      dtype='object')

In [5]:
# df = df_1.drop([ 'YR','Unnamed: 0','Unnamed: 0.1','DATE','TIME',
#                'SLAT','SLON','ELAT','ELON','LEN','ending county'], axis=1)

df = df_1.drop([ 'MO','Unnamed: 0','Unnamed: 0.1','YR','TIME',
              'SLAT','SLON','ELAT','ELON','LEN','ending county','starting county','Injuries','Fatalities','FID'], axis=1)

In [6]:
df
# Date, Starting county, property loss 

DATE  MAG  WID  Property Loss
0     2011-04-09    0   50            4.0
1     2011-04-09    1  150            5.0
2     2011-04-09    1  100            4.0
3     2011-04-09    0   50            4.0
4     2011-04-27    0   70            3.0
...          ...  ...  ...            ...
1103  2009-06-12    1   30            4.0
1104  2009-07-30    1  250            5.0
1107  2010-05-01    1  100            4.0
1110  1991-11-19    1   50            6.0
1113  2013-05-31    1  250            5.0

[686 rows x 4 columns]

In [7]:
# Create our features

target = 'MAG'
X = pd.get_dummies(df.drop(columns=target))


# Create our target
y = df[target]

In [8]:

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)

### Run through the Models Provided in the Module 17 

In [9]:
x ="An Error as occured"
try:

    print(f"naive random oversampling\n")
# Resample the training data with the RandomOversampler

    ros = RandomOverSampler(random_state=1)
    X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
    Counter(y_resampled)
# Train the Logistic Regression model using the resampled data
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Display the confusion matrix
    y_pred = model.predict(X_test)
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
except:
      print(x)



# Calculated the balanced accuracy score
try:

    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")

# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

# Resample the training data with SMOTE
    print(f"SMOTE\n")
    X_resampled, y_resampled = SMOTE(random_state=1,
    sampling_strategy='auto').fit_resample(
       X_train, y_train)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

except:
      print(x)
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
# Resample the training data with SMOTE

try: 
    print(f"Random Under Sampler\n")
    ros = RandomUnderSampler(random_state=1)
    X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:
      print(x)
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
# YOUR CODE HERE
try:
    print(f"SMOTEENN\n")
    smote_enn = SMOTEENN(random_state=0)
    X_resampled, y_resampled = smote_enn.fit_resample(X, y)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:  
      print(x)


# Resample the training data with the BalancedRandomForestClassifier
try:
    print(f"Balanced Random Forest Classifier \n")
    model = BalancedRandomForestClassifier(n_estimators =100, random_state=1)
    model = model.fit(X_train, y_train)
    # Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:
    print(x)

# Train the EasyEnsembleClassifier
try:
    print(f"Easy Ensemble Classifier \n")

# Train the EasyEnsembleClassifier
    from imblearn.ensemble import EasyEnsembleClassifier 
    model = EasyEnsembleClassifier(n_estimators =100, random_state=1)
    model.fit(X_train, y_train)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
    
except:
    print(x)

naive random oversampling

Confusion Matrix:
[[31  0  3  1  0  0]
 [32  0 10 21  1  0]
 [15  0  2 25  4  1]
 [ 4  0  0  9  5  2]
 [ 1  0  0  2  3  0]
 [ 0  0  0  0  0  0]]

The accuracy score: 
0.37565349544072946

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.37      0.89      0.62      0.53      0.74      0.56        35
          1       0.00      0.00      1.00      0.00      0.00      0.00        64
          2       0.13      0.04      0.90      0.06      0.20      0.03        47
          3       0.16      0.45      0.68      0.23      0.55      0.30        20
          4       0.23      0.50      0.94      0.32      0.69      0.45         6
          5       0.00      0.00      0.98      0.00      0.00      0.00         0

avg / total       0.14      0.26      0.85      0.16      0.29      0.17       172

SMOTE

An Error as occured
Random Under Sampler

The accuracy score: 
0.19972771023302938

Conf

### Additional Machine Learning Models that we can try 

#### SGDClassifier 

link to reference: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html

In [10]:
#sklearn.linear_model.SGDClassifier


# This estimator implements regularized linear models with stochastic gradient descent (SGD) learning: 
#     the gradient of the loss is estimated each sample at a time and the model is updated 
#     along the way with a decreasing strength schedule (aka learning rate).

from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
# X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
# Counter(y_resampled)

model = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3))
model.fit(X_train, y_train)

# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.48251963019250266

Confusion Matrix:
[[17 13  4  1  0  0]
 [ 9 45  9  1  0  0]
 [ 0 26 16  4  1  0]
 [ 0  5  3 11  0  1]
 [ 0  1  1  2  2  0]
 [ 0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.65      0.49      0.93      0.56      0.67      0.43        35
          1       0.50      0.70      0.58      0.58      0.64      0.42        64
          2       0.48      0.34      0.86      0.40      0.54      0.28        47
          3       0.58      0.55      0.95      0.56      0.72      0.50        20
          4       0.67      0.33      0.99      0.44      0.58      0.31         6
          5       0.00      0.00      0.99      0.00      0.00      0.00         0

avg / total       0.54      0.53      0.79      0.52      0.63      0.39       172



#### GaussianNB

link to reference: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

In [11]:
# When performing classification you often want to predict not only the class label, 
# but also the associated probability. 
# This probability gives you some kind of confidence on the prediction

from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import brier_score_loss
from sklearn.naive_bayes import GaussianNB

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

model = GaussianNB()
model.fit(X_train, y_train)  # GaussianNB itself does not support sample-weights


# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.3444617527862208

Confusion Matrix:
[[11  0  3  5 16]
 [19 10  1  4 30]
 [ 8  3  4  7 25]
 [ 2  1  0 10  7]
 [ 1  0  0  1  4]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.27      0.31      0.78      0.29      0.50      0.23        35
          1       0.71      0.16      0.96      0.26      0.39      0.14        64
          2       0.50      0.09      0.97      0.15      0.29      0.08        47
          3       0.37      0.50      0.89      0.43      0.67      0.43        20
          4       0.05      0.67      0.53      0.09      0.59      0.36         6

avg / total       0.50      0.23      0.90      0.25      0.42      0.18       172



 RandomOverSampler: Using differnt solvers

link to reference https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [12]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='liblinear', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.5385948581560285

Confusion Matrix:
[[21 10  3  1  0  0]
 [14 35 13  1  1  0]
 [ 6 16 10  3 11  1]
 [ 0  2  2 10  5  1]
 [ 0  0  0  1  5  0]
 [ 0  0  0  0  0  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.51      0.60      0.85      0.55      0.72      0.50        35
          1       0.56      0.55      0.74      0.55      0.64      0.40        64
          2       0.36      0.21      0.86      0.27      0.43      0.17        47
          3       0.62      0.50      0.96      0.56      0.69      0.46        20
          4       0.23      0.83      0.90      0.36      0.86      0.74         6
          5       0.00      0.00      0.99      0.00      0.00      0.00         0

avg / total       0.49      0.47      0.83      0.47      0.61      0.38       172

