In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
# from pathlib import Path
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN
from imblearn.ensemble import BalancedRandomForestClassifier



In [2]:
df = pd.read_csv('/Users/savannahposner/Desktop/bigProject/Messing_Around.csv')

In [3]:
df

Unnamed: 0    FID    YR  MO        DATE      TIME  MAG   LOSS     SLAT  \
0              0  23025  2011   4  2011-04-09  14:35:00    0  0.020  36.2971   
1              1  23027  2011   4  2011-04-09  16:00:00    1  0.075  36.3000   
2              2  23028  2011   4  2011-04-09  16:08:00    1  0.010  36.3037   
3              3  23029  2011   4  2011-04-09  16:15:00    0  0.015  36.0424   
4              4  23044  2011   4  2011-04-27  19:07:00    0  0.005  36.2255   
...          ...    ...   ...  ..         ...       ...  ...    ...      ...   
1109        1109  28915  1967   7  1967-07-05  14:25:00    1  4.000  35.0000   
1110        1110  28916  1991  11  1991-11-19  17:05:00    1  6.000  35.1300   
1111        1111  28926  1992   3  1992-03-18  08:20:00    0  4.000  35.2200   
1112        1112  28962  1974   6  1974-06-07  11:30:00    1  4.000  35.5700   
1113        1113  28984  2013   5  2013-05-31  05:05:00    1  0.180  35.6159   

         SLON     ELAT     ELON    LEN  WID  Fatalities  Injuries  
0    -82.3174  36.2934 -82.3021   0.89   50           0         0  
1    -82.4341  36.3000 -82.4341   3.00  150           0         0  
2    -82.3923  36.3099 -82.3846   0.61  100           0         0  
3    -82.5568  36.0477 -82.5393   1.04   50           0         0  
4    -83.0570  36.2263 -83.0486   0.50   70           0         0  
...       ...      ...      ...    ...  ...         ...       ...  
1109 -90.0000   0.0000   0.0000   0.10   10           0         0  
1110 -90.0200  35.2800 -89.9300  10.00   50           0         0  
1111 -89.7700   0.0000   0.0000   1.50   50           0         0  
1112 -89.6500   0.0000   0.0000   0.30  100           1         1  
1113 -89.7031  35.6142 -89.6884   0.83  250           0         0  

[1114 rows x 16 columns]

In [4]:
# Create our features

target = ''
X = pd.get_dummies(df.drop(columns=target))


# Create our target
y = df[target]

In [5]:

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)

### Run through the Models Provided in the Module 17 

In [6]:
x ="An Error as occured"
try:

    print(f"naive random oversampling\n")
# Resample the training data with the RandomOversampler

    ros = RandomOverSampler(random_state=1)
    X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
    Counter(y_resampled)
# Train the Logistic Regression model using the resampled data
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Display the confusion matrix
    y_pred = model.predict(X_test)
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
except:
      print(x)



# Calculated the balanced accuracy score
try:

    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")

# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

# Resample the training data with SMOTE
    print(f"SMOTE\n")
    X_resampled, y_resampled = SMOTE(random_state=1,
    sampling_strategy='auto').fit_resample(
       X_train, y_train)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

except:
      print(x)
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
# Resample the training data with SMOTE

try: 
    print(f"Random Under Sampler\n")
    ros = RandomUnderSampler(random_state=1)
    X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:
      print(x)
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
# YOUR CODE HERE
try:
    print(f"SMOTEENN\n")
    smote_enn = SMOTEENN(random_state=0)
    X_resampled, y_resampled = smote_enn.fit_resample(X, y)
    Counter(y_resampled)
    model = LogisticRegression(solver='lbfgs', random_state=1)
    model.fit(X_resampled, y_resampled)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:  
      print(x)


# Resample the training data with the BalancedRandomForestClassifier
try:
    print(f"Balanced Random Forest Classifier \n")
    model = BalancedRandomForestClassifier(n_estimators =100, random_state=1)
    model = model.fit(X_train, y_train)
    # Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
except:
    print(x)

# Train the EasyEnsembleClassifier
try:
    print(f"Easy Ensemble Classifier \n")

# Train the EasyEnsembleClassifier
    from imblearn.ensemble import EasyEnsembleClassifier 
    model = EasyEnsembleClassifier(n_estimators =100, random_state=1)
    model.fit(X_train, y_train)
# Calculated the balanced accuracy score
    y_pred = model.predict(X_test)
    balanced_accuracy_score(y_test, y_pred)
    print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
    print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")
    
except:
    print(x)

naive random oversampling

Confusion Matrix:
[[54 17  2  0  2]
 [49 39 21 11  5]
 [15 11 14  9  6]
 [ 2  3  4  5  4]
 [ 0  1  1  2  2]]

The accuracy score: 
0.37953131313131305

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.45      0.72      0.68      0.55      0.70      0.49        75
          1       0.55      0.31      0.79      0.40      0.50      0.24       125
          2       0.33      0.25      0.88      0.29      0.47      0.21        55
          3       0.19      0.28      0.92      0.22      0.50      0.24        18
          4       0.11      0.33      0.94      0.16      0.56      0.29         6

avg / total       0.45      0.41      0.79      0.40      0.55      0.30       279

SMOTE

An Error as occured
Random Under Sampler

The accuracy score: 
0.23743030303030302

Confusion Matrix:
[[46  8 18  3  0  0]
 [39 49 30  7  0  0]
 [13 31 10  0  1  0]
 [ 0 12  4  0  0  2]
 [ 0  3  2  0  0  1]


### Additional Machine Learning Models that we can try 

#### SGDClassifier 

link to reference: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html

In [7]:
#sklearn.linear_model.SGDClassifier


# This estimator implements regularized linear models with stochastic gradient descent (SGD) learning: 
#     the gradient of the loss is estimated each sample at a time and the model is updated 
#     along the way with a decreasing strength schedule (aka learning rate).

from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

model = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3))
model.fit(X_train, y_train)

# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.2507636363636364

Confusion Matrix:
[[21 48  6  0  0]
 [15 99 11  0  0]
 [ 7 34 10  2  2]
 [ 0 11  5  0  2]
 [ 0  4  1  1  0]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.49      0.28      0.89      0.36      0.50      0.23        75
          1       0.51      0.79      0.37      0.62      0.54      0.31       125
          2       0.30      0.18      0.90      0.23      0.40      0.15        55
          3       0.00      0.00      0.99      0.00      0.00      0.00        18
          4       0.00      0.00      0.99      0.00      0.00      0.00         6

avg / total       0.42      0.47      0.67      0.42      0.46      0.23       279



#### GaussianNB

link to reference: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

In [8]:
# When performing classification you often want to predict not only the class label, 
# but also the associated probability. 
# This probability gives you some kind of confidence on the prediction

from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import brier_score_loss
from sklearn.naive_bayes import GaussianNB

from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

model = GaussianNB()
model.fit(X_train, y_train)  # GaussianNB itself does not support sample-weights


# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.26202828282828283

Confusion Matrix:
[[22 13 14 16 10]
 [19 17 33 23 33]
 [ 5  4 24  7 15]
 [ 0  3  4  5  6]
 [ 0  0  1  4  1]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.48      0.29      0.88      0.36      0.51      0.24        75
          1       0.46      0.14      0.87      0.21      0.34      0.11       125
          2       0.32      0.44      0.77      0.37      0.58      0.32        55
          3       0.09      0.28      0.81      0.14      0.47      0.21        18
          4       0.02      0.17      0.77      0.03      0.36      0.12         6

avg / total       0.40      0.25      0.85      0.27      0.44      0.19       279



 RandomOverSampler: Using differnt solvers

link to reference https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [9]:

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)
# Train the Logistic Regression model using the resampled data

model = LogisticRegression(solver='liblinear', random_state=1)
    
#'liblinear’, ‘sag’, ‘saga
model.fit(X_resampled, y_resampled)
# Display the confusion matrix

y_pred = model.predict(X_test)
print(f"The accuracy score: \n{balanced_accuracy_score(y_test, y_pred)}\n")
# Display the confusion matrix
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")
# Print the imbalanced classification report
print(f"Classification Report:\n{classification_report_imbalanced(y_test, y_pred)}")

The accuracy score: 
0.40687676767676767

Confusion Matrix:
[[63  8  3  1  0]
 [53 32 28 11  1]
 [11 14 18 11  1]
 [ 0  0 10  5  3]
 [ 0  0  2  2  2]]

Classification Report:
                   pre       rec       spe        f1       geo       iba       sup

          0       0.50      0.84      0.69      0.62      0.76      0.59        75
          1       0.59      0.26      0.86      0.36      0.47      0.21       125
          2       0.30      0.33      0.81      0.31      0.51      0.25        55
          3       0.17      0.28      0.90      0.21      0.50      0.24        18
          4       0.29      0.33      0.98      0.31      0.57      0.31         6

avg / total       0.47      0.43      0.81      0.41      0.56      0.32       279

